//valores tabelados
const songs = [
  {
    cat: "Objetcs",
    cates: [
      {
        cat: "Dices",
        img: "dices.png",
        songs: [
          "dice01.mp3",
          "dice02.mp3",
          "dice03.mp3",
          "dice04.mp3",
          "dice05.mp3",
          "dice06.mp3",
          "dice07.mp3",
          "dice08.mp3",
          "dice09.mp3",
          "dice10.mp3",
        ],
      },
      {
        cat: "Clock",
        img: "relogio.png",
        songs: [
          "clock01.mp3",
          "clock02.mp3",
          "clock03.mp3",
          "clock04.mp3",
          "clock05.mp3",
          "clock06.mp3",
          "clock07.mp3",
          "clock08.mp3",
          "clock09.mp3",
          "clock10.mp3",
          "clock11.mp3",
          "clock12.mp3",
          "clock13.mp3",
          "clock14.mp3",
          "clock15.mp3",
          "clock16.mp3",
          "clock17.mp3",
          "clock18.mp3",
        ],
      },
      {
        cat: "Keyboard",
        img: "teclado.png",
        songs: [
          "keyboard01.mp3",
          "keyboard02.mp3",
          "keyboard03.mp3",
          "keyboard04.mp3",
          "keyboard05.mp3",
          "keyboard06.mp3",
          "keyboard07.mp3",
          "keyboard08.mp3",
        ],
      },
      {
        cat: "Cutlery",
        img: "talher.png",
        songs: [
          "cutlery01.mp3",
          "cutlery02.mp3",
          "cutlery03.mp3",
          "cutlery04.mp3",
          "cutlery05.mp3",
          "cutlery06.mp3",
          "cutlery07.mp3",
          "cutlery08.mp3",
          "cutlery09.mp3",
          "cutlery10.mp3",
        ],
      },
      {
        cat: "Alarms",
        img: "alarme.png",
        songs: [
          "alarme01.mp3",
          "alarme02.mp3",
          "alarme03.mp3",
          "alarme04.mp3",
          "alarme05.mp3",
          "alarme06.mp3",
          "alarme07.mp3",
          "alarme08.mp3",
          "alarme09.mp3",
          "alarme10.mp3",
          "alarme11.mp3",
          "alarme12.mp3",
          "alarme13.mp3",
          "alarme14.mp3",
          "alarme15.mp3",
          "alarme16.mp3",
          "alarme17.mp3",
          "alarme18.mp3",
          "alarme19.mp3",
          "alarme20.mp3",
          "alarme21.mp3",
          "alarme22.mp3",
          "alarme23.mp3",
          "alarme24.mp3",
          "alarme25.mp3",
          "alarme26.mp3",
          "alarme27.mp3",
          "alarme28.mp3",
          "alarme29.mp3",
          "alarme30.mp3",
          "alarme31.mp3",
          "alarme32.mp3",
          "alarme33.mp3",
          "alarme34.mp3",
          "alarme35.mp3",
        ],
      },
      { cat: "Toys", img: "toys.png", songs: ["toy01.mp3", "toy02.mp3"] },
    ],
  },
  {
    cat: "Environments",
    songs: [
      "environment01.mp3",
      "environment02.mp3",
      "environment03.mp3",
      "environment04.mp3",
      "environment05.mp3",
    ],
  },
  {
    cat: "Nature",
    cates: [
      {
        cat: "Rain",
        img: "chuva.png",
        songs: [
          "Rain01.mp3",
          "Rain02.mp3",
          "Rain03.mp3",
          "Rain04.mp3",
          "Rain05.mp3",
          "Rain06.mp3",
          "Rain07.mp3",
          "Rain08.mp3",
          "Rain09.mp3",
          "Rain10.mp3",
          "Rain11.mp3",
        ],
      },
      {
        cat: "Thunder",
        img: "raio.png",
        songs: ["Thunder01.mp3", "Thunder02.mp3", "Thunder03.mp3"],
      },
      {
        cat: "Fire",
        img: "fogo.png",
        songs: [
          "fire01.mp3",
          "fire02.mp3",
          "fire03.mp3",
          "fire04.mp3",
          "fire05.mp3",
          "fire06.mp3",
        ],
      },
      {
        cat: "Bonfire",
        img: "fogo.png",
        songs: [
          "bonfire01.mp3",
          "bonfire02.mp3",
          "bonfire03.mp3",
          "bonfire04.mp3",
          "bonfire05.mp3",
          "bonfire06.mp3",
        ],
      },
      {
        cat: "Wind",
        img: "vento.png",
        songs: [
          "wind01.mp3",
          "wind02.mp3",
          "wind03.mp3",
          "wind04.mp3",
          "wind05.mp3",
          "wind06.mp3",
          "wind07.mp3",
          "wind08.mp3",
          "wind09.mp3",
          "wind10.mp3",
          "wind11.mp3",
          "wind12.mp3",
          "wind13.mp3",
          "wind14.mp3",
          "wind15.mp3",
          "wind16.mp3",
          "wind17.mp3",
          "wind18.mp3",
          "wind19.mp3",
        ],
      },
      {
        cat: "River",
        img: "rio.png",
        songs: [
          "river01.mp3",
          "river02.mp3",
          "river03.mp3",
          "river04.mp3",
          "river05.mp3",
          "river06.mp3",
          "river07.mp3",
          "river08.mp3",
        ],
      },
      {
        cat: "Sea",
        img: "mar.png",
        songs: [
          "sea01.mp3",
          "sea02.mp3",
          "sea03.mp3",
          "sea04.mp3",
          "sea05.mp3",
          "sea06.mp3",
          "sea07.mp3",
          "sea08.mp3",
          "sea09.mp3",
          "sea10.mp3",
          "sea11.mp3",
          "sea12.mp3",
          "sea13.mp3",
        ],
      },
    ],
  },
  {
    cat: "Animals",
    cates: [
      {
        cat: "Dog",
        img: "cachorro.png",
        songs: [
          "dog01.mp3",
          "dog02.mp3",
          "dog03.mp3",
          "dog04.mp3",
          "dog05.mp3",
          "dog06.mp3",
          "dog07.mp3",
          "dog08.mp3",
          "dog09.mp3",
          "dog10.mp3",
          "dog11.mp3",
          "dog12.mp3",
          "dog13.mp3",
          "dog14.mp3",
          "dog15.mp3",
        ],
      },
      {
        cat: "Wolf",
        img: "lobo.png",
        songs: [
          "wolf01.mp3",
          "wolf02.mp3",
          "wolf03.mp3",
          "wolf04.mp3",
          "wolf05.mp3",
          "wolf06.mp3",
          "wolf07.mp3",
          "wolf08.mp3",
          "wolf09.mp3",
          "wolf10.mp3",
        ],
      },
      {
        cat: "Cat",
        img: "gato.png",
        songs: [
          "cat01.mp3",
          "cat02.mp3",
          "cat03.mp3",
          "cat04.mp3",
          "cat05.mp3",
          "cat06.mp3",
          "cat07.mp3",
          "cat08.mp3",
          "cat09.mp3",
          "cat10.mp3",
          "cat11.mp3",
        ],
      },
      {
        cat: "Bird",
        img: "passaro.png",
        songs: [
          "bird01.mp3",
          "bird02.mp3",
          "bird03.mp3",
          "bird04.mp3",
          "bird04.mp3",
          "bird05.mp3",
          "bird06.mp3",
          "bird07.mp3",
          "bird08.mp3",
          "bird09.mp3",
          "bird10.mp3",
          "bird11.mp3",
          "bird12.mp3",
          "bird13.mp3",
          "bird14.mp3",
          "bird15.mp3",
          "bird16.mp3",
          "bird17.mp3",
          "bird18.mp3",
        ],
      },
      {
        cat: "BigFeline",
        img: "leao.png",
        songs: [
          "feline01.mp3",
          "feline02.mp3",
          "feline03.mp3",
          "feline04.mp3",
          "feline05.mp3",
          "feline06.mp3",
          "feline07.mp3",
          "feline08.mp3",
          "feline09.mp3",
          "feline10.mp3",
          "feline11.mp3",
          "feline12.mp3",
          "feline13.mp3",
        ],
      },
      {
        cat: "Horse",
        img: "cavalo.png",
        songs: [
          "horse01.mp3",
          "horse02.mp3",
          "horse03.mp3",
          "horse04.mp3",
          "horse05.mp3",
          "horse06.mp3",
          "horse07.mp3",
          "horse08.mp3",
          "horse09.mp3",
          "horse10.mp3",
          "horse11.mp3",
        ],
      },
      {
        cat: "Cow",
        img: "vaca.png",
        songs: [
          "cow01.mp3",
          "cow02.mp3",
          "cow03.mp3",
          "cow04.mp3",
          "cow05.mp3",
          "cow06.mp3",
          "cow07.mp3",
        ],
      },
      {
        cat: "Chicken",
        img: "galinha.png",
        songs: [
          "chicken01.mp3",
          "chicken02.mp3",
          "chicken03.mp3",
          "chicken04.mp3",
          "chicken05.mp3",
          "chicken06.mp3",
          "chicken07.mp3",
          "chicken08.mp3",
          "chicken09.mp3",
          "chicken10.mp3",
          "chicken11.mp3",
          "chicken12.mp3",
          "chicken13.mp3",
        ],
      },
      {
        cat: "Duck",
        img: "pato.png",
        songs: [
          "duck01.mp3",
          "duck02.mp3",
          "duck03.mp3",
          "duck04.mp3",
          "duck05.mp3",
          "duck06.mp3",
          "duck07.mp3",
        ],
      },
    ],
  },
  {
    cat: "Actions",
    cates: [
      {
        cat: "Walk",
        img: "pegadas.png",
        songs: [
          "Walk01.mp3",
          "Walk02.mp3",
          "Walk03.mp3",
          "Walk04.mp3",
          "Walk05.mp3",
          "Walk06.mp3",
          "Walk07.mp3",
          "Walk08.mp3",
          "Walk09.mp3",
          "Walk10.mp3",
        ],
      },
      {
        cat: "Attack",
        img: "luta.png",
        songs: [
          "Attack_01.mp3",
          "Attack_02.mp3",
          "Attack_03.mp3",
          "Attack_04.mp3",
          "Attack_05.mp3",
          "Attack_06.mp3",
          "Attack_07.mp3",
          "Attack_08.mp3",
          "Attack_09.mp3",
          "Attack_10.mp3",
          "Attack_11.mp3",
          "Attack_12.mp3",
          "Attack_13.mp3",
        ],
      },
      {
        cat: "Death",
        img: "morte.png",
        songs: [
          "Death_01.mp3",
          "Death_02.mp3",
          "Death_03.mp3",
          "Death_04.mp3",
          "Death_05.mp3",
          "Death_06.mp3",
          "Death_07.mp3",
          "Death_08.mp3",
          "Death_09.mp3",
        ],
      },
      {
        cat: "Grunt",
        img: "raiva.png",
        songs: [
          "Grunt_01.mp3",
          "Grunt_02.mp3",
          "Grunt_03.mp3",
          "Grunt_04.mp3",
          "Grunt_05.mp3",
          "Grunt_06.mp3",
          "Grunt_07.mp3",
          "Grunt_08.mp3",
          "Grunt_09.mp3",
          "Grunt_10.mp3",
          "Grunt_11.mp3",
          "Grunt_12.mp3",
          "Grunt_13.mp3",
        ],
      },
      {
        cat: "Hurt",
        img: "ferimento.png",
        songs: [
          "Hurt_01.mp3",
          "Hurt_02.mp3",
          "Hurt_03.mp3",
          "Hurt_04.mp3",
          "Hurt_05.mp3",
          "Hurt_06.mp3",
          "Hurt_07.mp3",
          "Hurt_08.mp3",
          "Hurt_09.mp3",
        ],
      },
      {
        cat: "Laugh",
        img: "risada.png",
        songs: [
          "Laugh_01.mp3",
          "Laugh_02.mp3",
          "Laugh_03.mp3",
          "Laugh_04.mp3",
          "Laugh_05.mp3",
          "Laugh_06.mp3",
          "Laugh_07.mp3",
          "Laugh_08.mp3",
          "Laugh_09.mp3",
          "Laugh_10.mp3",
          "Laugh_11.mp3",
          "Laugh_12.mp3",
          "Laugh_13.mp3",
          "Laugh_14.mp3",
          "Laugh_15.mp3",
          "Laugh_16.mp3",
          "Laugh_17.mp3",
          "Laugh_18.mp3",
          "Laugh_19.mp3",
          "Laugh_20.mp3",
          "Laugh_21.mp3",
          "Laugh_22.mp3",
          "Laugh_23.mp3",
          "Laugh_24.mp3",
        ],
      },
      {
        cat: "Surprise",
        img: "surpresa.png",
        songs: [
          "Surprise_01.mp3",
          "Surprise_02.mp3",
          "Surprise_03.mp3",
          "Surprise_04.mp3",
          "Surprise_05.mp3",
          "Surprise_06.mp3",
          "Surprise_07.mp3",
          "Surprise_08.mp3",
          "Surprise_09.mp3",
          "Surprise_10.mp3",
          "Surprise_01.mp3",
          "Surprise_02.mp3",
          "Surprise_03.mp3",
          "Surprise_04.mp3",
          "Surprise_05.mp3",
          "Surprise_06.mp3",
          "Surprise_07.mp3",
          "Surprise_08.mp3",
          "Surprise_09.mp3",
          "Surprise_10.mp3",
          "Surprise_11.mp3",
          "Surprise_12.mp3",
          "Surprise_13.mp3",
          "Surprise_14.mp3",
          "Surprise_15.mp3",
          "Surprise_16.mp3",
          "Surprise_17.mp3",
          "Surprise_18.mp3",
          "Surprise_19.mp3",
          "Surprise_20.mp3",
          "Surprise_21.mp3",
          "Surprise_22.mp3",
          "Surprise_23.mp3",
          "Surprise_24.mp3",
          "Surprise_25.mp3",
          "Surprise_26.mp3",
          "Surprise_27.mp3",
          "Surprise_28.mp3",
          "Surprise_29.mp3",
          "Surprise_30.mp3",
          "Surprise_31.mp3",
          "Surprise_32.mp3",
          "Surprise_33.mp3",
          "Surprise_34.mp3",
          "Surprise_35.mp3",
          "Surprise_36.mp3",
          "Surprise_37.mp3",
          "Surprise_38.mp3",
          "Surprise_39.mp3",
          "Surprise_40.mp3",
        ],
      },
      {
        cat: "Cry",
        img: "choro.png",
        songs: [
          "Cry01.mp3",
          "Cry02.mp3",
          "Cry03.mp3",
          "Cry04.mp3",
          "Cry05.mp3",
          "Cry06.mp3",
          "Cry07.mp3",
          "Cry08.mp3",
          "Cry09.mp3",
          "Cry10.mp3",
          "Cry11.mp3",
          "Cry12.mp3",
          "Cry13.mp3",
          "Cry14.mp3",
          "Cry15.mp3",
          "Cry16.mp3",
          "Cry17.mp3",
          "Cry18.mp3",
          "Cry19.mp3",
          "Cry20.mp3",
          "Cry21.mp3",
          "Cry22.mp3",
          "Cry23.mp3",
          "Cry24.mp3",
          "Cry25.mp3",
          "Cry26.mp3",
          "Cry27.mp3",
          "Cry28.mp3",
          "Cry29.mp3",
          "Cry30.mp3",
        ],
      },
    ],
  },
  {
    cat: "Monsters",
    cates: [
      {
        cat: "Goblin",
        cates: [
          {
            cat: "Attack",
            img: "goblin.png",
            songs: [
              "Goblin_Attack_01.wav",
              "Goblin_Attack_02.wav",
              "Goblin_Attack_03.wav",
              "Goblin_Attack_04.wav",
              "Goblin_Attack_05.wav",
            ],
          },
          {
            cat: "Death",
            img: "goblin.png",
            songs: [
              "Goblin_Death_01.wav",
              "Goblin_Death_02.wav",
              "Goblin_Death_03.wav",
              "Goblin_Death_04.wav",
              "Goblin_Death_05.wav",
              "Goblin_Death_06.mp3",
            ],
          },
          {
            cat: "Grunt",
            img: "goblin.png",
            songs: [
              "Goblin_Grunt_01.wav",
              "Goblin_Grunt_02.wav",
              "Goblin_Grunt_03.wav",
              "Goblin_Grunt_04.wav",
              "Goblin_Grunt_05.wav",
            ],
          },
          {
            cat: "Hurt",
            img: "goblin.png",
            songs: [
              "Goblin_Hurt_01.wav",
              "Goblin_Hurt_02.wav",
              "Goblin_Hurt_03.wav",
              "Goblin_Hurt_04.wav",
              "Goblin_Hurt_05.wav",
            ],
          },
          {
            cat: "Idle",
            img: "goblin.png",
            songs: [
              "Goblin_Idle_01.wav",
              "Goblin_Idle_02.wav",
              "Goblin_Idle_03.wav",
              "Goblin_Idle_04.wav",
              "Goblin_Idle_05.wav",
            ],
          },
          {
            cat: "Laugh",
            img: "goblin.png",
            songs: [
              "Goblin_Laugh_01.wav",
              "Goblin_Laugh_02.wav",
              "Goblin_Laugh_03.wav",
              "Goblin_Laugh_04.wav",
              "Goblin_Laugh_05.wav",
            ],
          },
          {
            cat: "Surprise",
            img: "goblin.png",
            songs: [
              "Goblin_Surprise_01.wav",
              "Goblin_Surprise_02.wav",
              "Goblin_Surprise_03.wav",
              "Goblin_Surprise_04.wav",
              "Goblin_Surprise_05.wav",
            ],
          },
        ],
      },
      {
        cat: "Dragons",
        img: "dragao.png",
        songs: [
          "dragon01.mp3",
          "dragon02.mp3",
          "dragon03.mp3",
          "dragon04.mp3",
          "dragon05.mp3",
          "dragon06.mp3",
          "dragon07.mp3",
          "dragon08.mp3",
          "dragon09.mp3",
          "dragon10.mp3",
          "dragon11.mp3",
          "dragon12.mp3",
          "dragon13.mp3",
          "dragon14.mp3",
          "dragon15.mp3",
        ],
      },
      {
        cat: "Orc",
        img: "orc.png",
        songs: ["orc01.mp3", "orc02.mp3", "orc03.mp3"],
      },
    ],
  },
  {
    cat: "Battle",
    cates: [
      {
        cat: "Explosion",
        img: "explosao.png",
        songs: ["explosion01.mp3", "explosion02.mp3"],
      },
      {
        cat: "Shot",
        img: "tiro.png",
        songs: [
          "shot01.mp3",
          "shot02.mp3",
          "shot03.mp3",
          "shot04.mp3",
          "shot05.mp3",
          "shot06.mp3",
          "shot07.mp3",
          "shot08.mp3",
        ],
      },
      {
        cat: "Swords",
        img: "espadas.png",
        songs: [
          "sword01.mp3",
          "sword02.mp3",
          "sword03.mp3",
          "sword04.mp3",
          "sword05.mp3",
          "sword06.mp3",
          "sword07.mp3",
          "sword08.mp3",
        ],
      },
      { cat: "Laser", img: "laser.png", songs: ["laser01.mp3"] },
      {
        cat: "BattleCamp",
        songs: ["batlle01.mp3", "batlle02.mp3", "batlle03.mp3", "batlle04.mp3"],
      },
    ],
  },
];
const translats = {
  Attack: "Ataque",
  Death: "Morte",
  Grunt: "Grunhido",
  Hurt: "Ferido",
  Idle: "Parado",
  Laugh: "Risada",
  Surprise: "Surpresa",
  Actions: "Ações",
  Human: "Humano",
  Dices: "Dados",
  Nature: "Natureza",
  Rain: "Chuva",
  Thunder: "Trovão",
  Walk: "Andar",
  Fire: "Fogo",
  Bonfire: "Fogueira",
  Monsters: "Monstros",
  Battle: "Batalha",
  Explosion: "Explosão",
  Shot: "Tiro",
  Cry: "Choro",
  Swords: "Espadas",
  Animals: "Animais",
  Dragons: "Dragões",
  Objetcs: "Objetos",
  Clock: "Relógio",
  Keyboard: "Teclado",
  Dog: "Cachorro",
  Cat: "Gato",
  Bird: "Passaro",
  BigFeline: "Grande Felino",
  Horse: "Cavalo",
  Cow: "Vaca",
  River: "Rio",
  Sea: "Mar",
  Cutlery: "Talheres",
  Alarms: "Alarmes",
  Wind: "Vento",
  Chicken: "Galinha",
  Duck: "Pato",
  BattleCamp: "Campo",
  Environments: "Ambientes",
};
