//valores tabelados
const songs = [
  {
    cat: "Dices",
    img: "dices.png",
    songs: [
      "dice01.mp3",
      "dice02.mp3",
      "dice03.mp3",
      "dice04.mp3",
      "dice05.mp3",
      "dice06.mp3",
      "dice07.mp3",
      "dice08.mp3",
      "dice09.mp3",
      "dice10.mp3",
    ],
  },
  {
    cat: "Nature",
    cates: [
      {
        cat: "Rain",
        img: "chuva.png",
        songs: [
          "Rain01.mp3",
          "Rain02.mp3",
          "Rain03.mp3",
          "Rain04.mp3",
          "Rain05.mp3",
          "Rain06.mp3",
          "Rain07.mp3",
          "Rain08.mp3",
          "Rain09.mp3",
          "Rain10.mp3",
          "Rain11.mp3",
        ],
      },
      {
        cat: "Thunder",
        img: "raio.png",
        songs: ["Thunder01.mp3", "Thunder02.mp3", "Thunder03.mp3"],
      },
      {
        cat: "Fire",
        img: "fogo.png",
        songs: [
          "fire01.mp3",
          "fire02.mp3",
          "fire03.mp3",
          "fire04.mp3",
          "fire05.mp3",
          "fire06.mp3",
        ],
      },
      {
        cat: "Bonfire",
        img: "fogo.png",
        songs: [
          "bonfire01.mp3",
          "bonfire02.mp3",
          "bonfire03.mp3",
          "bonfire04.mp3",
          "bonfire05.mp3",
          "bonfire06.mp3",
        ],
      },
    ],
  },
  {
    cat: "Actions",
    cates: [
      {
        cat: "Walk",
        img: "pegadas.png",
        songs: [
          "Walk01.mp3",
          "Walk02.mp3",
          "Walk03.mp3",
          "Walk04.mp3",
          "Walk05.mp3",
          "Walk06.mp3",
          "Walk07.mp3",
          "Walk08.mp3",
          "Walk09.mp3",
          "Walk10.mp3",
        ],
      },
      {
        cat: "Attack",
        img: "luta.png",
        songs: [
          "Attack_01.mp3",
          "Attack_02.mp3",
          "Attack_03.mp3",
          "Attack_04.mp3",
          "Attack_05.mp3",
          "Attack_06.mp3",
          "Attack_07.mp3",
          "Attack_08.mp3",
          "Attack_09.mp3",
          "Attack_10.mp3",
          "Attack_11.mp3",
          "Attack_12.mp3",
          "Attack_13.mp3",
        ],
      },
      {
        cat: "Death",
        img: "morte.png",
        songs: [
          "Death_01.mp3",
          "Death_02.mp3",
          "Death_03.mp3",
          "Death_04.mp3",
          "Death_05.mp3",
          "Death_06.mp3",
          "Death_07.mp3",
          "Death_08.mp3",
          "Death_09.mp3",
        ],
      },
      {
        cat: "Grunt",
        img: "raiva.png",
        songs: [
          "Grunt_01.mp3",
          "Grunt_02.mp3",
          "Grunt_03.mp3",
          "Grunt_04.mp3",
          "Grunt_05.mp3",
          "Grunt_06.mp3",
          "Grunt_07.mp3",
          "Grunt_08.mp3",
          "Grunt_09.mp3",
          "Grunt_10.mp3",
          "Grunt_11.mp3",
          "Grunt_12.mp3",
          "Grunt_13.mp3",
        ],
      },
      {
        cat: "Hurt",
        img: "ferimento.png",
        songs: [
          "Hurt_01.mp3",
          "Hurt_02.mp3",
          "Hurt_03.mp3",
          "Hurt_04.mp3",
          "Hurt_05.mp3",
          "Hurt_06.mp3",
          "Hurt_07.mp3",
          "Hurt_08.mp3",
        ],
      },
      {
        cat: "Laugh",
        img: "risada.png",
        songs: [
          "Laugh_01.mp3",
          "Laugh_02.mp3",
          "Laugh_03.mp3",
          "Laugh_04.mp3",
          "Laugh_05.mp3",
          "Laugh_06.mp3",
          "Laugh_07.mp3",
          "Laugh_08.mp3",
          "Laugh_09.mp3",
          "Laugh_10.mp3",
          "Laugh_11.mp3",
          "Laugh_12.mp3",
          "Laugh_13.mp3",
          "Laugh_14.mp3",
          "Laugh_15.mp3",
          "Laugh_16.mp3",
          "Laugh_17.mp3",
          "Laugh_18.mp3",
          "Laugh_19.mp3",
          "Laugh_20.mp3",
          "Laugh_21.mp3",
        ],
      },
      {
        cat: "Surprise",
        img: "surpresa.png",
        songs: [
          "Surprise_01.mp3",
          "Surprise_02.mp3",
          "Surprise_03.mp3",
          "Surprise_04.mp3",
          "Surprise_05.mp3",
          "Surprise_06.mp3",
          "Surprise_07.mp3",
          "Surprise_08.mp3",
          "Surprise_09.mp3",
          "Surprise_10.mp3",
          "Surprise_01.mp3",
          "Surprise_02.mp3",
          "Surprise_03.mp3",
          "Surprise_04.mp3",
          "Surprise_05.mp3",
          "Surprise_06.mp3",
          "Surprise_07.mp3",
          "Surprise_08.mp3",
          "Surprise_09.mp3",
          "Surprise_10.mp3",
          "Surprise_11.mp3",
          "Surprise_12.mp3",
          "Surprise_13.mp3",
          "Surprise_14.mp3",
          "Surprise_15.mp3",
          "Surprise_16.mp3",
          "Surprise_17.mp3",
          "Surprise_18.mp3",
          "Surprise_19.mp3",
          "Surprise_20.mp3",
          "Surprise_21.mp3",
          "Surprise_22.mp3",
          "Surprise_23.mp3",
          "Surprise_24.mp3",
          "Surprise_25.mp3",
          "Surprise_26.mp3",
          "Surprise_27.mp3",
          "Surprise_28.mp3",
          "Surprise_29.mp3",
          "Surprise_30.mp3",
          "Surprise_31.mp3",
          "Surprise_32.mp3",
          "Surprise_33.mp3",
          "Surprise_34.mp3",
          "Surprise_35.mp3",
          "Surprise_36.mp3",
          "Surprise_37.mp3",
          "Surprise_38.mp3",
          "Surprise_39.mp3",
          "Surprise_40.mp3",
        ],
      },
      {
        cat: "Cry",
        img: "choro.png",
        songs: [
          "Cry01.mp3",
          "Cry02.mp3",
          "Cry03.mp3",
          "Cry04.mp3",
          "Cry05.mp3",
          "Cry06.mp3",
          "Cry07.mp3",
          "Cry08.mp3",
          "Cry09.mp3",
          "Cry10.mp3",
          "Cry11.mp3",
          "Cry12.mp3",
          "Cry13.mp3",
          "Cry14.mp3",
          "Cry15.mp3",
          "Cry16.mp3",
          "Cry17.mp3",
          "Cry18.mp3",
          "Cry19.mp3",
          "Cry20.mp3",
          "Cry21.mp3",
          "Cry22.mp3",
          "Cry23.mp3",
          "Cry24.mp3",
          "Cry25.mp3",
          "Cry26.mp3",
          "Cry27.mp3",
          "Cry28.mp3",
          "Cry29.mp3",
        ],
      },
    ],
  },
  {
    cat: "Monsters",
    cates: [
      {
        cat: "Goblin",
        cates: [
          {
            cat: "Attack",
            songs: [
              "Goblin_Attack_01.wav",
              "Goblin_Attack_02.wav",
              "Goblin_Attack_03.wav",
              "Goblin_Attack_04.wav",
              "Goblin_Attack_05.wav",
            ],
          },
          {
            cat: "Death",
            songs: [
              "Goblin_Death_01.wav",
              "Goblin_Death_02.wav",
              "Goblin_Death_03.wav",
              "Goblin_Death_04.wav",
              "Goblin_Death_05.wav",
              "Goblin_Death_06.mp3",
            ],
          },
          {
            cat: "Grunt",
            songs: [
              "Goblin_Grunt_01.wav",
              "Goblin_Grunt_02.wav",
              "Goblin_Grunt_03.wav",
              "Goblin_Grunt_04.wav",
              "Goblin_Grunt_05.wav",
            ],
          },
          {
            cat: "Hurt",
            songs: [
              "Goblin_Hurt_01.wav",
              "Goblin_Hurt_02.wav",
              "Goblin_Hurt_03.wav",
              "Goblin_Hurt_04.wav",
              "Goblin_Hurt_05.wav",
            ],
          },
          {
            cat: "Idle",
            songs: [
              "Goblin_Idle_01.wav",
              "Goblin_Idle_02.wav",
              "Goblin_Idle_03.wav",
              "Goblin_Idle_04.wav",
              "Goblin_Idle_05.wav",
            ],
          },
          {
            cat: "Laugh",
            songs: [
              "Goblin_Laugh_01.wav",
              "Goblin_Laugh_02.wav",
              "Goblin_Laugh_03.wav",
              "Goblin_Laugh_04.wav",
              "Goblin_Laugh_05.wav",
            ],
          },
          {
            cat: "Surprise",
            songs: [
              "Goblin_Surprise_01.wav",
              "Goblin_Surprise_02.wav",
              "Goblin_Surprise_03.wav",
              "Goblin_Surprise_04.wav",
              "Goblin_Surprise_05.wav",
            ],
          },
        ],
      },
    ],
  },
  {
    cat: "Battle",
    cates: [
      { cat: "Explosion", img: "explosao.png", songs: ["explosion01.mp3"] },
      {
        cat: "Shot",
        img: "tiro.png",
        songs: [
          "shot01.mp3",
          "shot02.mp3",
          "shot03.mp3",
          "shot04.mp3",
          "shot05.mp3",
          "shot06.mp3",
          "shot07.mp3",
        ],
      },
    ],
  },
];
const translats = {
  Attack: "Ataque",
  Death: "Morte",
  Grunt: "Grunhido",
  Hurt: "Ferido",
  Idle: "Parado",
  Laugh: "Risada",
  Surprise: "Surpresa",
  Actions: "Ações",
  Human: "Humano",
  Dices: "Dados",
  Nature: "Natureza",
  Rain: "Chuva",
  Thunder: "Trovão",
  Walk: "Andar",
  Fire: "Fogo",
  Bonfire: "Fogueira",
  Monsters: "Monstros",
  Battle: "Batalha",
  Explosion: "Explosão",
  Shot: "Tiro",
};
